[build]
  # Build command
  command = "npm run build"
  
  # Output directory (where Next.js puts the static files)
  publish = "out"

[build.environment]
  # Node version and build settings
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Handle client-side routing for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"